# templates/hashicorp-vault/policy.hcl
# ─────────────────────────────────────
# HSED-aware Vault Transit policy template.
# Generated by: hsed generate vault --policy <file> --role <role> --mount transit --key <key>
#
# Copy and rename per role, e.g.:
#   signer.hcl     (hsed:12 / HS--)
#   vault.hcl      (hsed:3  / --ED)
#   audit.hcl      (hsed:9  / H--D)
#
# Apply with:
#   vault policy write hsed-signer signer.hcl

# ── hsed:signer (12 / HS--) ────────────────────────────────────────────────

# Create HMACs
path "transit/hmac/{{KEY_NAME}}" {
  capabilities = ["update"]
}

# Read key metadata
path "transit/keys/{{KEY_NAME}}" {
  capabilities = ["read"]
}

# Create signatures
path "transit/sign/{{KEY_NAME}}" {
  capabilities = ["update"]
}

# Verify signatures and MACs
path "transit/verify/{{KEY_NAME}}" {
  capabilities = ["update"]
}

# ── Deny all admin operations ───────────────────────────────────────────────
# Vault uses deny-by-default, so these are implicit — listed for clarity.

# path "transit/keys/{{KEY_NAME}}" {
#   capabilities = ["create", "update", "delete"]  # NOT granted to signer
# }

# ── Notes ───────────────────────────────────────────────────────────────────
# Replace {{KEY_NAME}} with your actual transit key name, or use * for wildcard.
# Replace {{MOUNT}} with your transit secret engine mount path (default: transit).
#
# To generate this file for any HSED role:
#   hsed generate vault \
#     --policy production.hsed \
#     --role signer \
#     --mount transit \
#     --key my-signing-key \
#     --output signer.hcl

