"""
hsed.integrations.vault
───────────────────────
Translate HSED Policies → HashiCorp Vault HCL policy documents.

Vault uses a path-capability model. HSED bits map to Transit secret engine
capabilities:

    H (Hash/Verify)  → transit/verify/*, transit/keys/* (read)  → ["read"]
    S (Sign)         → transit/sign/*                           → ["update"]
    E (Encrypt)      → transit/encrypt/*                        → ["update"]
    D (Decrypt)      → transit/decrypt/*                        → ["update"]

Usage:

    from hsed import Policy, Role
    from hsed.integrations.vault import VaultGenerator

    policy = Policy('prod')
    policy.add_role(Role('signer', permissions=12))

    gen = VaultGenerator(policy)
    hcl = gen.generate(role='signer', mount='transit')
    print(hcl)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ..core.permissions import Bit, Role, active_bits, permission_string
from ..core.policy import Policy


# ---------------------------------------------------------------------------
# Vault path mapping
# ---------------------------------------------------------------------------

@dataclass
class VaultPath:
    path: str
    capabilities: list[str]
    comment: str = ""

    def to_hcl(self) -> str:
        caps = json_list(self.capabilities)
        lines = []
        if self.comment:
            lines.append(f"# {self.comment}")
        lines.append(f'path "{self.path}" {{')
        lines.append(f"  capabilities = {caps}")
        lines.append("}")
        return "\n".join(lines)


def json_list(items: list[str]) -> str:
    quoted = ", ".join(f'"{i}"' for i in sorted(set(items)))
    return f"[{quoted}]"


# Mapping: Bit → list of (path_template, capabilities)
# path_template uses {mount} and {key_name} placeholders
_BIT_PATHS: dict[Bit, list[tuple[str, list[str], str]]] = {
    Bit.HASH: [
        ("{mount}/verify/{key_name}",  ["update"], "Verify signatures and MACs"),
        ("{mount}/keys/{key_name}",    ["read"],   "Read key metadata"),
    ],
    Bit.SIGN: [
        ("{mount}/sign/{key_name}",    ["update"], "Create signatures"),
        ("{mount}/hmac/{key_name}",    ["update"], "Create HMACs"),
        ("{mount}/keys/{key_name}",    ["read"],   "Read key metadata"),
    ],
    Bit.ENCRYPT: [
        ("{mount}/encrypt/{key_name}", ["update"], "Encrypt plaintext"),
        ("{mount}/rewrap/{key_name}",  ["update"], "Rewrap ciphertext"),
        ("{mount}/keys/{key_name}",    ["read"],   "Read key metadata"),
    ],
    Bit.DECRYPT: [
        ("{mount}/decrypt/{key_name}", ["update"], "Decrypt ciphertext"),
        ("{mount}/keys/{key_name}",    ["read"],   "Read key metadata"),
    ],
}


def _paths_for_permissions(
    permissions: int,
    *,
    mount: str,
    key_name: str,
) -> list[VaultPath]:
    """Return deduplicated VaultPath list for a permission mask."""
    seen: dict[str, set[str]] = {}  # path → set of capabilities
    comments: dict[str, list[str]] = {}

    for bit in active_bits(permissions):
        for path_tpl, caps, comment in _BIT_PATHS.get(bit, []):
            path = path_tpl.format(mount=mount, key_name=key_name)
            if path not in seen:
                seen[path] = set()
                comments[path] = []
            seen[path].update(caps)
            if comment not in comments[path]:
                comments[path].append(comment)

    return [
        VaultPath(
            path=p,
            capabilities=sorted(c),
            comment=" | ".join(comments[p]),
        )
        for p, c in sorted(seen.items())
    ]


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

@dataclass
class VaultPolicyDocument:
    """A Vault HCL policy document for one HSED role."""

    role_name: str
    permissions: int
    mount: str
    key_name: str
    paths: list[VaultPath]
    policy_name: str = ""

    def to_hcl(self) -> str:
        label = permission_string(self.permissions)
        header = "\n".join([
            f"# HSED Policy: {self.policy_name or self.role_name}",
            f"# Role:        {self.role_name}",
            f"# Permissions: {label} ({self.permissions})",
            f"# Transit:     {self.mount}/{self.key_name}",
            "#",
            "# Generated by hsed, do not edit manually.",
            "",
        ])
        blocks = "\n\n".join(p.to_hcl() for p in self.paths)
        return header + blocks + "\n"

    def metadata(self) -> dict:
        return {
            "hsed_role": self.role_name,
            "hsed_permissions": self.permissions,
            "hsed_label": permission_string(self.permissions),
            "vault_mount": self.mount,
            "vault_key": self.key_name,
        }


class VaultGenerator:
    """
    Generates HashiCorp Vault HCL policy documents from an HSED Policy.

    Parameters
    ----------
    policy:
        The HSED Policy containing roles to translate.

    Examples
    --------
    >>> from hsed import Policy, Role
    >>> from hsed.integrations.vault import VaultGenerator
    >>> p = Policy('ci')
    >>> p.add_role(Role('signer', permissions=12))
    >>> gen = VaultGenerator(p)
    >>> hcl = gen.generate(role='signer', mount='transit', key_name='ci-key')
    >>> 'transit/sign/ci-key' in hcl.to_hcl()
    True
    """

    def __init__(self, policy: Policy) -> None:
        self.policy = policy

    def generate(
        self,
        *,
        role: str,
        mount: str = "transit",
        key_name: str = "*",
    ) -> VaultPolicyDocument:
        """
        Generate a Vault HCL policy document for a single role.

        Parameters
        ----------
        role:
            Name of the role in the Policy.
        mount:
            Vault Transit secret engine mount path (default: 'transit').
        key_name:
            Key name within the mount. Use '*' for wildcard access.
        """
        resolved: Role = self.policy.get_role(role)
        paths = _paths_for_permissions(
            resolved.permissions, mount=mount, key_name=key_name
        )
        return VaultPolicyDocument(
            role_name=resolved.name,
            permissions=resolved.permissions,
            mount=mount,
            key_name=key_name,
            paths=paths,
            policy_name=self.policy.name,
        )

    def generate_all(
        self,
        *,
        mount: str = "transit",
        key_name: str = "*",
    ) -> dict[str, VaultPolicyDocument]:
        """Generate Vault HCL policy documents for all roles."""
        return {
            role.name: self.generate(role=role.name, mount=mount, key_name=key_name)
            for role in self.policy.roles()
        }
