# templates/aws-kms/main.tf
# ─────────────────────────
# HSED-aware AWS KMS key with per-role IAM policies.
# Roles and their allowed actions are derived from HSED permission masks —
# generated by: hsed generate aws-kms --policy <file> --role <role> --key-arn <arn>
#
# Usage:
#   terraform init
#   terraform apply -var="project=my-project" -var="env=production"

terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
}

# ── KMS Key ────────────────────────────────────────────────────────────────

resource "aws_kms_key" "hsed" {
  description             = "${var.project}-${var.env} HSED-governed key"
  deletion_window_in_days = var.deletion_window_days
  enable_key_rotation     = true
  key_usage               = "SIGN_VERIFY"   # or "ENCRYPT_DECRYPT" — set per use case
  customer_master_key_spec = var.key_spec

  policy = data.aws_iam_policy_document.key_policy.json

  tags = merge(var.tags, {
    "hsed:policy"  = var.hsed_policy_name
    "hsed:managed" = "true"
    Environment    = var.env
    Project        = var.project
  })
}

resource "aws_kms_alias" "hsed" {
  name          = "alias/${var.project}-${var.env}"
  target_key_id = aws_kms_key.hsed.key_id
}

# ── Key Policy ─────────────────────────────────────────────────────────────
# Root access is required by AWS for all KMS keys.
# Role-specific statements are generated from HSED permission masks.

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "key_policy" {
  # Required: root account access
  statement {
    sid     = "EnableRootAccess"
    effect  = "Allow"
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
    actions   = ["kms:*"]
    resources = ["*"]
  }

  # hsed:signer (12 / HS--) — CI/CD pipelines, code signing
  dynamic "statement" {
    for_each = length(var.signer_principal_arns) > 0 ? [1] : []
    content {
      sid    = "HSEDHSAllow"
      effect = "Allow"
      principals {
        type        = "AWS"
        identifiers = var.signer_principal_arns
      }
      actions = [
        "kms:DescribeKey",
        "kms:GetPublicKey",
        "kms:Sign",
        "kms:Verify",
      ]
      resources = ["*"]
    }
  }

  # hsed:vault (3 / --ED) — secrets management
  dynamic "statement" {
    for_each = length(var.vault_principal_arns) > 0 ? [1] : []
    content {
      sid    = "HSEDEDAllow"
      effect = "Allow"
      principals {
        type        = "AWS"
        identifiers = var.vault_principal_arns
      }
      actions = [
        "kms:Decrypt",
        "kms:DescribeKey",
        "kms:Encrypt",
        "kms:GenerateDataKey",
      ]
      resources = ["*"]
    }
  }

  # hsed:audit (9 / H--D) — compliance, forensics
  dynamic "statement" {
    for_each = length(var.audit_principal_arns) > 0 ? [1] : []
    content {
      sid    = "HSEDHDAllow"
      effect = "Allow"
      principals {
        type        = "AWS"
        identifiers = var.audit_principal_arns
      }
      actions = [
        "kms:Decrypt",
        "kms:DescribeKey",
        "kms:Verify",
      ]
      resources = ["*"]
    }
  }

  # Always deny destructive operations — no role overrides this
  statement {
    sid    = "HSEDDenyDestructive"
    effect = "Deny"
    principals {
      type        = "AWS"
      identifiers = ["*"]
    }
    actions = [
      "kms:DeleteAlias",
      "kms:DeleteImportedKeyMaterial",
      "kms:DisableKey",
      "kms:ScheduleKeyDeletion",
    ]
    resources = ["*"]
    condition {
      test     = "StringNotEquals"
      variable = "aws:PrincipalArn"
      values   = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
  }
}

# ── IAM Policies (attachable to roles/users) ───────────────────────────────

resource "aws_iam_policy" "hsed_signer" {
  count       = length(var.signer_principal_arns) > 0 ? 1 : 0
  name        = "${var.project}-${var.env}-hsed-signer"
  description = "HSED signer role (HS--/12): Sign and Verify via KMS"
  policy      = data.aws_iam_policy_document.signer_policy.json
  tags        = var.tags
}

data "aws_iam_policy_document" "signer_policy" {
  statement {
    sid    = "HSEDHSAllow"
    effect = "Allow"
    actions = [
      "kms:DescribeKey",
      "kms:GetPublicKey",
      "kms:Sign",
      "kms:Verify",
    ]
    resources = [aws_kms_key.hsed.arn]
  }
}

resource "aws_iam_policy" "hsed_vault" {
  count       = length(var.vault_principal_arns) > 0 ? 1 : 0
  name        = "${var.project}-${var.env}-hsed-vault"
  description = "HSED vault role (--ED/3): Encrypt and Decrypt via KMS"
  policy      = data.aws_iam_policy_document.vault_policy.json
  tags        = var.tags
}

data "aws_iam_policy_document" "vault_policy" {
  statement {
    sid    = "HSEDEDAllow"
    effect = "Allow"
    actions = [
      "kms:Decrypt",
      "kms:DescribeKey",
      "kms:Encrypt",
      "kms:GenerateDataKey",
    ]
    resources = [aws_kms_key.hsed.arn]
  }
}

